<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InternalsVisibleTo>OpsMonitor.Api.Tests</InternalsVisibleTo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\OpsMonitor.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\OpsMonitor.Infrastructure.csproj" />
    <ProjectReference Include="..\Contracts\OpsMonitor.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

</Project>

